# Numpy

### demo01

In [2]:
import numpy as np

In [17]:
nd1 = np.array([[1,2,3],[4,7,9]])
# type(nd1)
nd1


array([[1, 2, 3],
       [4, 7, 9]])

In [26]:
nd1.shape

(2, 3)

In [27]:
nd1.ndim

2

In [28]:
nd1.size

6

### demo02

In [31]:
nd2 = np.zeros((3,5))
nd2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
# nd3= np.array(nd2) 
# nd3= np.asarray(nd2) #浅拷贝
nd3= np.copy(nd2) # deep copy

nd3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
nd4 = np.linspace(0,10,5)
nd4

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [51]:
nd5 = np.random.uniform(0,1,10)
nd5

array([0.24563117, 0.32837148, 0.42388679, 0.06426151, 0.43420228,
       0.75335767, 0.33699309, 0.09327397, 0.25748932, 0.583623  ])

In [54]:
nd6 = np.random.normal(loc=1.75,scale=0.1,size=100)
nd6

array([1.64505472, 1.71229526, 1.79068536, 1.52440934, 1.78713449,
       1.60841797, 1.80712711, 1.65438615, 1.78278823, 1.66829422,
       1.76685133, 1.88444055, 1.79398611, 1.72235016, 1.91272144,
       1.66229193, 1.75508531, 1.7246013 , 1.62083178, 1.90204526,
       1.65597399, 1.81047801, 1.75488914, 1.71685679, 1.87907821,
       1.76971296, 1.72202189, 1.73895595, 1.82790056, 1.64129344,
       1.76213238, 1.58195987, 1.8068753 , 1.87874668, 1.79768348,
       1.79221299, 1.93926555, 1.81935189, 1.74779059, 1.93341856,
       1.86113024, 1.65962229, 1.89850027, 1.75015359, 1.87341044,
       1.65686411, 1.83349306, 1.65835674, 1.84283068, 1.56049812,
       1.80492055, 1.82851213, 1.72953152, 1.51307631, 1.66646813,
       1.75030791, 1.84350315, 1.71867165, 1.77788996, 1.5801986 ,
       1.90457183, 1.86811853, 1.93675449, 1.74103489, 1.74778789,
       1.68066979, 1.660053  , 1.76949951, 1.83335323, 1.76120789,
       1.64039482, 1.72422076, 1.83831923, 1.70285501, 1.87379

### demo04

In [55]:
nd4 = np.array([ [[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]] ])
nd4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [56]:
nd4[1,0,2]

33

In [57]:
nd4.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6, 11, 22],
       [33, 44, 55, 66]])

In [58]:
nd4.T

array([[[ 1, 11],
        [ 4, 44]],

       [[ 2, 22],
        [ 5, 55]],

       [[ 3, 33],
        [ 6, 66]]])

In [59]:
nd4.tostring()

b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00\x16\x00\x00\x00\x00\x00\x00\x00!\x00\x00\x00\x00\x00\x00\x00,\x00\x00\x00\x00\x00\x00\x007\x00\x00\x00\x00\x00\x00\x00B\x00\x00\x00\x00\x00\x00\x00'

In [61]:
np.unique(nd4)
# set(nd4.flatten())

{1, 2, 3, 4, 5, 6, 11, 22, 33, 44, 55, 66}

### demo05

In [63]:
nd5 = np.random.normal(loc=0,scale=1,size=(8,10))
nd5

array([[ 0.83501535, -0.64113151,  1.43574861, -0.14139947,  0.51987739,
        -0.69143298, -0.56806751,  0.11740374,  1.47010204, -0.32684315],
       [ 0.13845926, -0.83129336, -1.11193708, -0.70652275,  0.52717692,
        -0.84182601,  1.57024937, -0.52781815, -0.72295138, -0.48601027],
       [-0.91808671,  0.99345867,  0.25232358, -0.19711787, -0.55285595,
        -2.91988456,  0.34386228, -1.28633459, -0.52623173,  0.75680943],
       [-1.16639172, -0.13852432,  0.33744558, -1.27758365, -0.98310101,
         0.25702449,  0.70294757, -0.25221974,  1.47229622,  0.81751858],
       [ 0.22925516,  0.50746933, -1.92229033, -2.34824276, -1.5413246 ,
        -2.01522025, -0.68944674, -0.56091848, -0.27995292,  0.95647863],
       [ 0.69097597,  1.0972573 ,  0.37645817,  1.43733879, -0.53411433,
        -1.52787366, -0.83610718,  0.16244525, -0.82410423,  0.02958921],
       [-1.97517243, -0.59993539,  1.39754225,  0.33474562,  0.40015953,
         0.72546435, -0.20634789, -0.83533213